
# render.yaml

services:
  - name: web
    buildCommand: pip install -r requirements.txt
    start:
  - cd Back
  - gunicorn myproj.wsgi:application -b 0.0.0.0:$PORT
    env:
      - key: PYTHON_VERSION
        value: 3.8.1
